# Generated by Django 5.2.11 on 2026-02-05 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_user_id", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("type", models.CharField(max_length=50)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "app_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=200)),
                ("amount", models.FloatField()),
                ("whatsapp_number", models.CharField(max_length=20)),
                ("donation_type", models.CharField(max_length=50)),
                ("received_by", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_by_user_id", models.IntegerField()),
                ("created_by_name", models.CharField(max_length=100)),
                ("mandal_name", models.CharField(max_length=100)),
                ("client_donation_id", models.CharField(max_length=50, unique=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "donations",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                ("payment_mode", models.CharField(max_length=50)),
                ("paid_to", models.CharField(max_length=100)),
                ("created_by_user_id", models.IntegerField()),
                ("created_by_name", models.CharField(max_length=100)),
                ("mandal_name", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("client_expense_id", models.CharField(max_length=50, unique=True)),
                ("is_synced", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "expenses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_user_id", models.IntegerField()),
                ("to_manager_id", models.IntegerField()),
                ("mandal_name", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "wallet_transfers",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mandal_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("Manager", "Manager"), ("User", "User")],
                        max_length=20,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("is_demo_user", models.BooleanField(default=True)),
                (
                    "subscription_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_end_date", models.DateTimeField(blank=True, null=True)),
                ("payment_id", models.CharField(blank=True, max_length=100, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("donation_count", models.IntegerField(default=0)),
                ("expense_count", models.IntegerField(default=0)),
                ("entry_count", models.IntegerField(default=0)),
                ("wallet_balance", models.FloatField(default=0)),
                ("total_collected", models.FloatField(default=0)),
                ("total_transferred", models.FloatField(default=0)),
                ("manager_balance", models.FloatField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "ganesh_users",
                "indexes": [
                    models.Index(
                        fields=["mobile"], name="ganesh_user_mobile_8bb6c8_idx"
                    ),
                    models.Index(
                        fields=["mandal_name"], name="ganesh_user_mandal__fbaa32_idx"
                    ),
                    models.Index(fields=["role"], name="ganesh_user_role_f75358_idx"),
                ],
            },
        ),
    ]
