# Generated by Django 5.2.11 on 2026-02-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("donor_name", models.CharField(max_length=200)),
                ("amount", models.FloatField()),
                ("whatsapp_number", models.CharField(max_length=20)),
                ("donation_type", models.CharField(max_length=50)),
                ("received_by", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_by_user_id", models.IntegerField()),
                ("created_by_name", models.CharField(max_length=100)),
                ("mandal_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "donations",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                ("payment_mode", models.CharField(max_length=50)),
                ("paid_to", models.CharField(max_length=100)),
                ("created_by_user_id", models.IntegerField()),
                ("created_by_name", models.CharField(max_length=100)),
                ("mandal_name", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "expenses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AppNotification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("to_user_id", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("type", models.CharField(max_length=50)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "app_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_user_id"], name="app_notific_to_user_2774c9_idx"
                    ),
                    models.Index(fields=["type"], name="app_notific_type_2e0b80_idx"),
                    models.Index(
                        fields=["is_read"], name="app_notific_is_read_d57e70_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mandal_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[("Manager", "Manager"), ("User", "User")],
                        max_length=20,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("is_demo_user", models.BooleanField(default=True)),
                (
                    "subscription_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_end_date", models.DateTimeField(blank=True, null=True)),
                ("payment_id", models.CharField(blank=True, max_length=100, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("donation_count", models.IntegerField(default=0)),
                ("expense_count", models.IntegerField(default=0)),
                ("entry_count", models.IntegerField(default=0)),
                ("wallet_balance", models.FloatField(default=0)),
                ("total_collected", models.FloatField(default=0)),
                ("total_transferred", models.FloatField(default=0)),
                ("manager_balance", models.FloatField(default=0)),
            ],
            options={
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["mobile"], name="users_mobile_6f2369_idx"),
                    models.Index(
                        fields=["mandal_name"], name="users_mandal__aa713e_idx"
                    ),
                    models.Index(fields=["role"], name="users_role_0ace22_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WalletTransfer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("from_user_id", models.IntegerField()),
                ("to_manager_id", models.IntegerField()),
                ("mandal_name", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "wallet_transfers",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["mandal_name"], name="wallet_tran_mandal__62a284_idx"
                    ),
                    models.Index(
                        fields=["status"], name="wallet_tran_status_15b3bd_idx"
                    ),
                    models.Index(
                        fields=["from_user_id"], name="wallet_tran_from_us_d3f7a5_idx"
                    ),
                    models.Index(
                        fields=["to_manager_id"], name="wallet_tran_to_mana_85493a_idx"
                    ),
                ],
            },
        ),
    ]
